import { IBusinessDocument } from '../../models/business.model';
import { BusinessDto } from '../../dtos/business/business.dto';

export class BusinessMapper {
  static toDto(doc: IBusinessDocument): BusinessDto {
    return {
      id: doc._id.toString(),
      ownerId: doc.ownerId ? doc.ownerId.toString() : null,
      contactEmail: doc.contactEmail,
      passwordHash: doc.passwordHash,
      isPasswordSet: doc.isPasswordSet,
      name: doc.name,
      username: doc.username,
      tagline: doc.tagline,
      description: doc.description,
      establishedYear: doc.establishedYear,
      gstNumber: doc.gstNumber,
      contactPerson: doc.contactPerson,
      phone: doc.phone,
      email: doc.email,
      websiteUrl: doc.websiteUrl,
      whatsappNumber: doc.whatsappNumber,
      mobileNumbers: doc.mobileNumbers || [],
      landlineNumbers: doc.landlineNumbers || [],
      emails: doc.emails || [],
      address: doc.address,
      pincode: doc.pincode,
      plotNo: doc.plotNo,
      buildingName: doc.buildingName,
      streetName: doc.streetName,
      landmark: doc.landmark,
      area: doc.area,
      city: doc.city,
      state: doc.state,
      latitude: doc.latitude,
      longitude: doc.longitude,
      googleMapsUrl: doc.googleMapsUrl,
      timings: doc.timings,
      primaryCategory: doc.primaryCategory,
      subCategories: doc.subCategories || [],
      amenities: doc.amenities || [],
      parking: doc.parking,
      logo: doc.logo,
      coverPhoto: doc.coverPhoto,
      images: doc.images || [],
      socialLinks: doc.socialLinks,
      isVerified: doc.isVerified,
      status: doc.status,
      createdAt: doc.createdAt,
      updatedAt: doc.updatedAt,
    };
  }
}
