export { createAuthRouter } from './auth.routes';
export { createBusinessesRouter } from './businesses.routes';
export { createBusinessAuthRouter } from './business-auth.routes';
export { createAdminRouter } from './admin.routes';
export { createPostsRouter } from './posts.routes';
export { createFlashDealsRouter } from './flash-deals.routes';
export { createLocationRouter } from './location.routes';
export { createParkingRouter } from './parking.routes';
export { createAdminAuthRouter } from './admin-auth.routes';
